makautparser/urls.py
from django.contrib import admin
from django.urls import path,include
from wbut import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("wbut.urls")),
]

wbut/urls.py
from django.contrib import admin
from django.urls import path,include
from wbut import views
from django.contrib.sitemaps.views import sitemap
from wbut.sitemap import StaticViewSitemap
from . import views
from django.views.generic import TemplateView



app_name = 'wbut'

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('', views.index, name="home"),
    path('colleges',views.collegeList,name="colleges"),
    path('view-result/<roll_no>/<semester>', views.viewResult, name="viewResult"),
    path('class-result/<roll_no>/<semester>', views.viewClassRank, name="viewClassResult"),
    path('result-page/', views.resultOverview, name="resultPage"),
    path('time-table/', views.timeTable, name="timeTable"),
    path('download-time-table/<scheme>/<semester>', views.downloadTimeTable, name="downloadTimeTable"),
    path('download-pdf/<roll_no>/<semester>', views.export, name="downloadPdf"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    path('contact-us', views.contactUs, name="contactUs"),
    path('privacy-policy', views.privacyPolicy, name="privacyPolicy"),
    path('about-us', views.aboutUs, name="aboutUs"),
    path('robots.txt', TemplateView.as_view(template_name="wbut/robots.txt", content_type='text/plain')),

]

wbut/models.py
from django.db import models


# Create your models here.
class BasicDetails(models.Model):
    name = models.CharField(max_length=50)
    reg_no = models.CharField(max_length=100)
    roll_no = models.CharField(max_length=20,primary_key=True)
    college = models.CharField(max_length=100)

    class Meta:
        db_table = "basicDetails"


class SemesterOverview(models.Model):
    basicDetails = models.ForeignKey(BasicDetails, on_delete=models.CASCADE)
    semester = models.IntegerField()
    ygpa = models.CharField(max_length=20)
    cgpa = models.CharField(max_length=20)
    status = models.CharField(max_length=10)

    class Meta:
        db_table = "semOverview"
        unique_together = ('basicDetails', 'semester')


class Result(models.Model):
    basicDetails = models.ForeignKey(BasicDetails, on_delete=models.CASCADE)
    subject_code = models.CharField(max_length=10)
    subject_name = models.CharField(max_length=150)
    letter_grade = models.CharField(max_length=1)
    points = models.IntegerField()
    credit = models.FloatField()
    credit_points = models.FloatField()
    semester = models.CharField(max_length=20)

    class Meta:
        db_table = "result"


class College(models.Model):
    collegeCode = models.IntegerField(primary_key=True)
    collegeName = models.CharField(max_length=250)

    class Meta:
        db_table = "colleges"


class TimeTable(models.Model):
    date = models.CharField(max_length=20)
    time = models.CharField(max_length=30)
    sem = models.IntegerField()
    subject_code = models.CharField(max_length=50)
    subject_name = models.CharField(max_length=150)
    scheme = models.CharField(max_length=10)

wbut/views.py
from django.shortcuts import render
from wbut.parser import parseIndexPage, parseResult, parseCollegeList, downloadResult, parseimeTable, downloadTimeTableParse
from django.shortcuts import redirect
from django.http import HttpResponse
from wbut.semesterYear import getSemYear
from wbut.models import Result, BasicDetails, College, SemesterOverview, TimeTable
import urllib3
import logging

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
logger = logging.getLogger(__name__)


def resultOverview(request):
    if request.method == "POST":
        try:
            roll_no = request.POST['usn']
            sem = request.POST['sem']
            result_overview = SemesterOverview.objects.filter(semester=sem).filter(basicDetails_id=roll_no)
            if result_overview.count() <= 0:
                cookie, token = parseIndexPage()
                parseResult(roll_no, sem, cookie, token)
            basic_details = BasicDetails.objects.get(roll_no=roll_no)
            results = SemesterOverview.objects.filter(basicDetails=basic_details).order_by('-semester')
            semesterYear = []
            year = int(roll_no[6:8])
            for result in results:
                semester = int(result.semester)
                semYear = getSemYear(year, semester)
                semesterYear.append(semYear)
            mylist = zip(results, semesterYear)
            mylist2 = zip(results, semesterYear)
            retry = False
            context = {"results": mylist, "details": basic_details, "semesters": semesterYear, "results2": mylist2,
                       "retry": retry, "roll_no":roll_no, "sem":sem}
            return render(request, "wbut/result_overview.html", context)
        except TimeoutError as e:
            logger.info("TimeOut Error has Ocuured")
            try:
                basic_details = BasicDetails.objects.get(roll_no=roll_no)
                results = SemesterOverview.objects.filter(basicDetails=basic_details).order_by('-semester')
                semesterYear = []
                year = int(roll_no[6:8])
                for result in results:
                    semester = int(result.semester)
                    semYear = getSemYear(year, semester)
                    semesterYear.append(semYear)
                mylist = zip(results, semesterYear)
                mylist2 = zip(results, semesterYear)
                retry = True
                context = {"results": mylist, "details": basic_details, "semesters": semesterYear, "results2": mylist2,
                           "retry":retry, "roll_no":roll_no, "sem":sem}
                return render(request, "wbut/result_overview.html", context)
            except:
                retry = True
                context = {
                           "retry": retry, "roll_no": roll_no, "sem": sem}
                return render(request, "wbut/result_overview.html",context)
        except Exception as ex:
            logger.error(ex)
            return render(request, "wbut/error.html")
    else:
        return redirect("wbut:home")


# This renders the first page of the website
def index(request):
    return render(request, "wbut/index.html")


def viewResult(request, roll_no, semester):
    result = Result.objects.filter(basicDetails_id=roll_no).filter(semester=semester)
    total_credits = 0
    total_credit_points = 0
    for eachResult in result:
        total_credits += eachResult.credit
        total_credit_points += eachResult.credit_points
    basic_details = BasicDetails.objects.get(roll_no=roll_no)
    overview = SemesterOverview.objects.filter(basicDetails_id=roll_no).get(semester=semester)
    context = {"results": result, "details": basic_details, "overview": overview,
               "total_credits": total_credits, "total_credit_points": total_credit_points}
    return render(request, "wbut/result_page.html", context)


def collegeList(request):
    # parseCollegeList()
    colleges = College.objects.all()
    coll = {"colleges": colleges}
    return render(request, "wbut/colleges.html", coll)


def timeTable(request):
    if request.method == 'POST':
        scheme = request.POST['STREAM']
        semester = request.POST['SEMCODE']
        try:
            timeTable = TimeTable.objects.filter(scheme=scheme).filter(sem=semester)
            if timeTable.count() <= 0:
                cookie,token = parseIndexPage()
                parseimeTable(cookie,token,scheme,semester)
            timeTableDetails = TimeTable.objects.filter(scheme=scheme).filter(sem=semester)
            context = {'timeTable':timeTableDetails,'scheme':scheme, 'semester':semester}
            return render(request,"wbut/routine.html",context)
        except Exception as e:
            print(e)
            context = {'scheme': scheme, 'semester':semester}
            return render(request,"wbut/routine-error.html",context)

    else:
        return render(request,"wbut/time-table.html")


def viewClassRank(request, roll_no, semester):
    try:
        roll_no = roll_no[:-3]
        overview = SemesterOverview.objects.filter(basicDetails__roll_no__contains=roll_no).filter(
            semester=semester).order_by('-cgpa')
        for over in overview:
            print(over.basicDetails.name)
        context = {'results': overview, 'semester': semester}
        return render(request, "wbut/class_result.html", context)
    except Exception as e:
        logger.error(e)
        return render(request, "wbut/error.html")


def export(request,roll_no, semester):
    filename = roll_no + "-" + semester + ".pdf"
    cookie, token = parseIndexPage()
    f = downloadResult(roll_no, semester, cookie, token)
    response = HttpResponse(f.read(), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=' + filename
    response['Content-Type'] = 'application/pdf; charset=utf-16'
    return response


def downloadTimeTable(request,scheme, semester):
    filename = scheme + "-" + semester + ".pdf"
    cookie, token = parseIndexPage()
    f = downloadTimeTableParse(scheme, semester, cookie, token)
    response = HttpResponse(f.read(), content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=' + filename
    response['Content-Type'] = 'application/pdf; charset=utf-16'
    return response


def contactUs(request):
    return render(request,"wbut/contact-us.html")


def privacyPolicy(request):
    return render(request,"wbut/privacy-policy.html")


def aboutUs(request):
    return render(request,"wbut/about-us.html")

wbut/templates/wbut/base.html
<!DOCTYPE html>
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="Makaut Result | Wbut Result | Class Rank" />
    <meta property="og:url" content="https://makautresult.in" />
    <meta property="og:type" content="Makaut Result" />
    <meta property="og:description" content="Makaut Result, Wbut Result, Makaut Results by class, Check Your Class Rank" />
    {% block extra_head_tags %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-163126873-1"></script>
    <script>
     window.dataLayer = window.dataLayer || [];
     function gtag(){dataLayer.push(arguments);}
     gtag('js', new Date());

     gtag('config', 'UA-163126873-1');
    </script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block extra_head_after %}{% endblock %}

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'wbut:home' %}">MAKAUT RESULTS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'wbut:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'wbut:timeTable' %}">Time Table</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'wbut:colleges' %}">Colleges</a>
            </li>

        </ul>

    </div>
</nav>


{% block content %}

{% endblock %}
<!-- Footer -->
<footer class="page-footer bg-dark">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 text-center">
                <a href="{% url 'wbut:contactUs' %}">Contact Us</a>&nbsp;&nbsp;
                <a href="{% url 'wbut:aboutUs' %}">About Us</a>&nbsp;&nbsp;
                <a href="{% url 'wbut:privacyPolicy' %}">Privacy Policy</a>
            </div>
        </div>
    </div>


</footer>
<!-- Footer -->
{% block extra_script %}
{% endblock %}
</body>
</html>

wbut/templates/wbut/class_result.html
{% extends 'wbut/base.html' %}
{% block extra_head_tags %}
    <title>Class Result</title>
{% endblock %}
{% block content %}
<div class="container">
		<div class="table-responsive">
		<table class="table table-hover css-serial">
			<tr class="bg-dark text-center">
				<th colspan="6" style="color:white;">CLASS RESULT</td>
			</tr>
			<tr class="bg-primary text-center">
				<th colspan="6" style="color:white;">SEMESTER : {{ semester }}</th>
			</tr>
			<tr>
				<th>#</th>
				<th>Name</th>
                <th>Roll No</th>
				<th>SGPA</th>
			</tr>
			{% for result in results %}
			<tr>
                <td></td>
				<td><a href="{% url 'wbut:viewResult' result.basicDetails_id semester %}">{{ result.basicDetails.name }}</a></td>
				<td>{{ result.basicDetails_id }}</td>
				<td>{{ result.cgpa }}</td>

			</tr>
			{% endfor %}

		</table>
			</div>
	</div>
	{% endblock %}

wbut/templates/wbut/contact-us.html
{% extends 'wbut/base.html' %}
    {% block extra_head_tags %}
    <title>Contact Us</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-xs-12 col-sm-12 col-md-8">
            <div class="form-container">

                <h4>Get In Touch With Us</h4>
                <p class="mb-10">Enter Your Details & Message Below</p>
                <form class="result-form" action="{% url 'wbut:resultPage' %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">

                        <input type="text" class="form-control" name="usn" placeholder="Enter Your Name">
                    </div>
                     <div class="form-group">

                        <input type="email" class="form-control" name="usn" placeholder="Enter Your Email">
                    </div>
                    <div class="form-group">

                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Enter Message"></textarea>

                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
        </div>
        <div class="col-md-2">

        </div>

    </div>
</div>
{% endblock %}

wbut/templates/wbut/index.html
{% extends 'wbut/base.html' %}
    {% block extra_head_tags %}
    <title>Makaut Result | Wbut Result</title>
    <meta property="og:title" content="Makaut Result | Wbut Result | Class Rank" />
    <meta property="og:url" content="https://makautresult.in" />
    <meta property="og:type" content="Makaut Result" />
    <meta property="og:description" content="Makaut Result, Wbut Result, Makaut Results by class, Check Your Class Rank" />
    <meta name="description" content="Check MAKAUT result for all the semester. Check your class rank list, Previous semester and Revaluation results here." />
    <meta name="keywords" content="makaut result, makaut class rank, class rank list, wbut result, makaut previous semester results, makaut revaluation results,  makaut rank, makaut result odd sem, wbut result 2020, previous, makaut exam results, makautresult.in" />
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="d-none d-sm-block col-sm-6 image-container">
            <img class="images" alt="Responsive image" src="/static/images/image.png"/>
        </div>
        <div class="col-sm-6">
            <div class="form-container">

                <h3>MAKAUT RESULT</h3>
                <p class="mb-10">Use your Roll Number to check your result.</p>
                <form class="result-form" action="{% url 'wbut:resultPage' %}" method="POST">
                    {% csrf_token %}

                    <div class="form-group">

                        <input type="text" class="form-control" name="usn" aria-describedby="emailHelp"
                               placeholder="Enter Roll Number" pattern="[0-9]+" title="Only Numbers Allowed">
                    </div>
                    <div class="form-group">
                        <select class="form-control" name="sem" required>
                            <option selected disabled value="">Choose Your Semester</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

wbut/templates/wbut/result_overview.html
{% extends 'wbut/base.html' %}
{% block extra_head_tags %}
    <title>Results</title>
{% endblock %}
{% block content %}
<div class="container">
    {% if retry %}
    <div class="row">
        <div class="col-8 text-center">
        <h2>Server Too Busy</h2>
            <h4>Retry to get the latest result</h4>
        <form method="POST" action="{% url 'wbut:resultPage' %}">
            {% csrf_token %}
            <input type="hidden" name="usn" value="{{ roll_no }}">
            <input type="hidden" name="sem" value="{{ sem }}">
            <input type="submit" class="btn btn-primary" value="RETRY">
        </form>
            <hr />
            <br />
        </div>

    </div>
    {% endif %}
    {% if details %}
    <div class="row">
		<div class="col-3 font-weight-bold">NAME</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.name }}</div>
	</div>
	<div class="row">
		<div class="col-3 font-weight-bold">Roll No</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.roll_no }}</div>
	</div>
	<div class="row">
			<div class="col-3 font-weight-bold">College</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.college }}</div>
	</div>
    {% endif %}
    <div class="d-none d-sm-block">
        <div class="row">

            <div class="col-md-9 table-responsive">
                {% for result,semester in results %}

                <table class="table table-hover">
                    <tr class="bg-dark">
                        <th colspan="5" style="color:white;">{{ semester }}
                        </th>
                    </tr>


                    <tr>
                        <td>Semester</td>
                        <td>SGPA</td>
                        <td>YGPA</td>
                        <td>View Result</td>
                        <td>Class Result</td>
                    </tr>

                    <tr>
                        <td>{{ result.semester }}</td>
                        <td>{{ result.cgpa }}</td>
                        <td>{{ result.ygpa }}</td>
                        <td><a href="{% url 'wbut:viewResult' details.roll_no result.semester %}">
                            <button class="btn btn-primary">View Result</button>
                        </a></td>
                        <td><a href="{% url 'wbut:viewClassResult' details.roll_no result.semester %}">
                            <button class="btn btn-success">Class Result</button>
                        </a></td>
                    </tr>

                </table>

                {% endfor %}

            </div>
            <div class="col-md-3 table-responsive">
                <table class="table table-hover">
                    <tr class="bg-dark">
                        <td style="color:white;">ANNOUNCEMENT</td>
                    </tr>
                    <tr>
                        <td><a href="">7th Semester Results Announced</a></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="d-block d-sm-none">
        {% for result,semester in results2 %}
        <div class="card-body">
            <div class="row mb-2 bg-dark  text-center"
                 style="height:40px; justify-content: center;align-content: center;color: white;">
                <div class="col"> {{ semester }}</div>
            </div>
            <hr class="mt-0 mb-0" style="background-color:#ddd;">
            <div class="row mb-1 text-center">

                <div class="col column">
                    <small class="text-muted">Semester</small><br/>
                    {{ result.semester }}
                </div>
                <div class="col column">
                    <small class="text-muted">SGPA</small><br/>
                    {{ result.cgpa }}
                </div>
                <div class="col column3">
                    <small class="text-muted">YGPA</small><br/>
                    {{ result.ygpa }}
                </div>
            </div>
            <hr class="mt-0 mb-0" style="background-color:#ddd;">
            <div class="row mb-1 text-center">

                <div class="col column2">
                    <small class="text-muted">View Result</small><br/>
                    <a href="{% url 'wbut:viewResult' details.roll_no result.semester %}">
                        <button class="btn btn-primary">View Result</button>
                    </a>
                </div>
                <div class="col column3">
                    <small class="text-muted">Class Result</small><br/>
                    <a href="{% url 'wbut:viewClassResult' details.roll_no result.semester %}">
                        <button class="btn btn-success">Class Result</button>
                    </a>
                </div>

            </div>


        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}

wbut/templates/wbut/result_page.html
{% extends 'wbut/base.html' %}
{% block extra_head_tags %}
    <title>Result Page</title>
{% endblock %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-3 font-weight-bold">NAME</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.name }}</div>
	</div>
	<div class="row">
		<div class="col-3 font-weight-bold">Roll No</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.roll_no }}</div>
	</div>
	<div class="row">
			<div class="col-3 font-weight-bold">College</div>
		<div class="col-9">:&nbsp;&nbsp;{{ details.college }}</div>
	</div>
	<br/>

	<div class="d-none d-sm-block">
		<div class="table-responsive">
			<table class="table table-hover">
				<tr class="bg-dark">
					<th colspan="6" style="color:white;">Result
					</td>
				</tr>
				<tr style="background: lightgray;">
					<td colspan="2" style="color:white; background: blue;">Semester : {{ overview.semester }}</td>
					<td colspan="2" style="color:white; background: red;">SGPA : {{ overview.cgpa }}</td>
					{% ifnotequal overview.status ' ' %}
					<td colspan="2" style="color:white; background: green;">Result : {{ overview.status }}</td>
					{% endifnotequal %}

				</tr>
				<tr>
					<td>Subject Code</td>
					<td>Subject Name</td>
					<td>Letter Grade</td>
					<td>Points</td>
					<td>Credit</td>
					<td>Credit Points</td>
				</tr>
				{% for result in results %}
				<tr>
					<td>{{ result.subject_code }}</td>
					<td>{{ result.subject_name }}</td>
					<td>{{ result.letter_grade }}</td>
					<td>{{ result.points }}</td>
					<td>{{ result.credit }}</td>
					<td>{{ result.credit_points }}</td>
				</tr>
				{% endfor %}
				<tr style="background: lightgray;">
					<td colspan="4">Total : {{ total_credit_points }}</td>
					<td colspan="2">Credits : {{ total_credits }}</td>
				</tr>
			</table>
		</div>
		<div class="row mb-2 text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				<a href="{% url 'wbut:downloadPdf' details.roll_no overview.semester %}">
                            <button class="btn btn-success"style="width:100%">Download Result</button>
                        </a>
			</div>
		</div>
	</div>

	<div class="d-block d-sm-none">
		<div class="row mb-2 bg-dark text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				SEMESTER : &nbsp;{{ overview.semester }}
			</div>
		</div>
		<div class="row mb-2 bg-success text-center" style="height:40px; justify-content: center;align-content: center;color: white;">

			<div class="col" style="border-right:1px solid white;">
				CGPA : &nbsp;{{ overview.cgpa }}
			</div>
			{% ifnotequal overview.status ' ' %}
			<div class="col">
				RESULT : &nbsp;{{ overview.status }}
			</div>
			{% endifnotequal %}
		</div>
		{% for result in results %}
		<div class="card-body">
			<div class="row mb-1 text-center">
				<div class="col"><span class="text-muted">{{ result.subject_code }}</span>&nbsp;&nbsp;
					{{ result.subject_name }}
				</div>
			</div>
			<hr class="mt-0 mb-0">
			<div class="row mb-1 text-center">
				<div class="col column">
					<small class="text-muted">Letter Grade</small><br/>
					{{ result.letter_grade }}
				</div>
				<div class="col column3">
					<small class="text-muted">Points</small><br/>
					{{ result.points }}
				</div>
			</div>

			<hr class="mt-0 mb-0">

			<div class="row mb-1 text-center">

				<div class="col column2">
					<small class="text-muted">Credits</small><br/>
					{{ result.credit }}
				</div>
				<div class="col column3">
					<small class="text-muted">Credit Point</small><br/>
					{{ result.credit_points }}
				</div>

			</div>


		</div>
		{% endfor %}


		<div class="card-body">

			<div class="row mb-1 text-center">

				<div class="col column">
					<small class="text-muted">SGPA</small><br/>
					{{ overview.cgpa }}
				</div>
				<div class="col column3">
					<small class="text-muted">Total Points</small><br/>
					{{ total_credit_points }}
				</div>

			</div>
			<hr class="mt-0 mb-0">

			<div class="row mb-1 text-center">
				<div class="col">
					<small class="text-muted">Credits</small><br/>
					{{ total_credits }}
				</div>

			</div>

		</div>
		<div class="row mb-2 text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				<a href="{% url 'wbut:downloadPdf' details.roll_no overview.semester %}">
                            <button class="btn btn-success"style="width:100%">Download Result</button>
                        </a>
			</div>
		</div>
	</div>
</div>
{% endblock %}
	

wbut/templates/wbut/routine-error.html
<!DOCTYPE html>
{% extends 'wbut/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>
                    Oops!</h1>
                <h2>
                    Time Table Not Found</h2>
                <div class="error-details">
                    Time Table has not been announced for {{ scheme }} scheme for semester {{ semester }}

                </div>
                <div class="error-actions">
                    <a href="{% url 'wbut:home' %}" class="btn btn-primary btn-lg"><span
                            class="glyphicon glyphicon-home"></span>
                        Take Me Home </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

wbut/templates/wbut/routine.html
{% extends 'wbut/base.html' %}
{% block extra_head_tags %}
    <title>Makaut Time Table</title>
{% endblock %}
{% block content %}
<div class="container">
	<div class="d-none d-sm-block">
		<div class="table-responsive">
			<table class="table table-hover">
				<tr class="bg-dark">
					<th colspan="6" style="color:white;" class="text-center">STREAM : {{ scheme }}
					</th>
				</tr>
				<tr style="background: lightgray;">
					<th colspan="6" style="color:white; background: blue;" class="text-center">SEMESTER : {{ semester }}</th>

				</tr>
				<tr>
					<th>Date</th>
					<th>Time</th>
					<th>Subject Code</th>
					<th>Subject Name</th>
				</tr>
				{% for details in timeTable %}
				<tr>
					<td>{{ details.date }}</td>
					<td>{{ details.time }}</td>
					<td>{{ details.subject_code }}</td>
					<td>{{ details.subject_name }}</td>
				</tr>
				{% endfor %}
			</table>

		</div>
		<div class="row mb-2 text-center" style="height:40px;color: white;">
			<div class="col">
				<a href="{% url 'wbut:downloadTimeTable' scheme semester %}">
                            <button class="btn btn-success"style="width:50%">Download Time Table</button>
                        </a>
			</div>
		</div>
	</div>

	<div class="d-block d-sm-none">
		<div class="row mb-2 bg-dark text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				STREAM : &nbsp;{{ scheme }}
			</div>
		</div>
		<div class="row mb-2 bg-primary text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				SEMESTER : {{ semester }}
			</div>
		</div>
		{% for details in timeTable %}
		<div class="card-body">
			<div class="row mb-1 text-center">
				<div class="col"><span class="text-muted">{{ details.subject_code }}</span>&nbsp;&nbsp;
					{{ details.subject_name }}
				</div>
			</div>
			<hr class="mt-0 mb-0">
			<div class="row mb-1 text-center">
				<div class="col column">
					<small class="text-muted">Date</small><br/>
					{{ details.date }}
				</div>
				<div class="col column3">
					<small class="text-muted">Time</small><br/>
					{{ details.time }}
				</div>
			</div>

		</div>
		{% endfor %}
		<div class="row mb-2 text-center" style="height:40px; justify-content: center;align-content: center;color: white;">
			<div class="col">
				<a href="{% url 'wbut:downloadTimeTable' scheme semester %}">
                            <button class="btn btn-success"style="width:100%">Download Time Table</button>
                        </a>
			</div>
		</div>

	</div>
</div>
{% endblock %}
	